----- LOOP

DECLARE
    v_SEGMERCADO CLIENTE.SEGMERCADO_ID%type := 1;
    v_ID CLIENTE.ID%type; 
    CURSOR cur_CLIENTE IS SELECT ID FROM CLIENTE;
BEGIN
    OPEN cur_CLIENTE; 
    LOOP
        FETCH cur_CLIENTE INTO v_ID;
    EXIT WHEN cur_CLIENTE%NOTFOUND;
        ATUALIZAR_SEGMERCADO(v_ID, v_SEGMERCADO);
    END LOOP;
    CLOSE cur_CLIENTE;
END;

---- WHILE

DECLARE
    v_SEGMERCADO CLIENTE.SEGMERCADO_ID%type := 2;
    v_ID CLIENTE.ID%type; 
    CURSOR cur_CLIENTE IS SELECT ID FROM CLIENTE;
BEGIN
    OPEN cur_CLIENTE; 
    FETCH cur_CLIENTE INTO v_ID;
    WHILE cur_CLIENTE%FOUND LOOP
        ATUALIZAR_SEGMERCADO(v_ID, v_SEGMERCADO);
        FETCH cur_CLIENTE INTO v_ID;
   END LOOP;
    
    CLOSE cur_CLIENTE;

END;

---- FOR

DECLARE
    v_SEGMERCADO CLIENTE.SEGMERCADO_ID%type := 3;
    CURSOR cur_CLIENTE IS SELECT ID FROM CLIENTE;
BEGIN
    
    FOR linha_cur_cliente IN cur_CLIENTE LOOP
    ATUALIZAR_SEGMERCADO (linha_cur_cliente.ID, v_SEGMERCADO );
  
  END LOOP;
END;
 